platform:
  - x64

# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

skip_tags: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

# set clone depth
clone_depth: 5 # clone entire repository history if not defined

# to run your custom scripts instead of automatic tests
# test_script:
#  - npm run test-dapp
#  - npm run test  

# scripts that run after cloning repository
install:
  - ps: Install-Product node 8 x64
  - ps: $env:DEBUG = "electron-builder"
  - npm i -g --production windows-build-tools
  - cd dapp && rm -rf node_modules && rm package-lock.json && yarn add secp256k1 && yarn install && cd ..

# to run your custom scripts instead of automatic MSBuild
build_script:
  - cd dapp/ && mkdir dist && yarn run build-win

# scripts to run before deployment
before_deploy:
  - chmod +x prepare_deploy_win.sh
  - prepare_deploy_win.sh

deploy:
  provider: S3
  access_key_id: "{ACCESS_KEY_ID}"
  secret_access_key: "{SECRET_ACCESS_KEY}"
  bucket: wallet-desktop-builds
  region: eu-east-1
  artifact: /dapp/dist/multisigweb*.exe