# branches to build
branches:
  # whitelist
  only:
    - master
    - develop

skip_tags: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

# set clone depth
clone_depth: 5 # clone entire repository history if not defined

# to run your custom scripts instead of automatic tests
test_script:
  - npm run test-dapp
  - npm run test  

# scripts that run after cloning repository
install:
  - npm install && cd dapp && npm install && cd ..

# to run your custom scripts instead of automatic MSBuild
build_script:
  - chmod +x prepare_deploy.sh
  - ./prepare_deploy.sh